FROM python:latest

WORKDIR /app

COPY requirements.txt .
RUN pip3 install -r requirements.txt

COPY db_queries.py .
COPY Overview.py .

COPY main_logo.png .
COPY side_logo.png .

RUN mkdir -p /app/pages
COPY pages/Subscribe.py /app/pages/Subscribe.py
COPY pages/Magnitude_Predictor.py /app/pages/Magnitude_Predictor.py

EXPOSE 8501

CMD ["streamlit", "run", "Overview.py"]
